providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --force"]

[phases.build]
cmds = ["npm install @rollup/rollup-linux-x64-gnu --force && npm run build:client"]

[start]
cmd = "npm start"