services:
  - type: web
    name: restaurant-wine-management
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/health

databases:
  - name: restaurant-db
    plan: free
    databaseName: restaurant_wines
    user: restaurant_admin